### ISSUE TITLE
I am not able to change the key

### ISSUE THREAD

**Issue by Kakashiiiiy** [ying17zi/vim-live-latex-preview#3]
How can I change the \ mapping I got the DE layout.

**Comment by Kakashiiiiy** [comment]
I`ve read the doc but i dont know where to place the text

**Comment by ying17zi** [comment]
The key mapping is around the line 190 in
`ftplugin/tex/live-latex-preview.vim`.
You can define yours similarly in `.vimrc`

Best,
Hongying

**Comment by ying17zi** [comment]
Take a look at https://github.com/lervag/vimtex. 
With `latexmk`, you can also achieve the same effect as this plugin.

Previously I used LaTeX-Box but now vimtex.
